---
driver:
  name: docker
  use_sudo: false

provisioner:
  # name of the host
  hosts: test-kitchen
  # use an ansible playbook to provision our server
  name: ansible_playbook
  ansible_verbose: false
  require_ansible_repo: false
  require_ansible_omnibus: true
  ansible_version: 1.9.6
  require_chef_for_busser: false
  requirements_path: requirements.yml
  sudo: true

transport:
  max_ssh_sessions: 3

platforms:
  - name: ubuntu-16.04
    driver_config:
      run_command: /sbin/init
      dockerfile: .docker/xenial/Dockerfile
      platform: ubuntu
      instance_name: test-role-ansible-openssh-xenial64
      cap_add:
        - SYS_ADMIN
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      run_options:
        tmpfs:
        - /tmp
        - /run

verifier:
  name: serverspec
  sudo_path: true

suites:
  # suites found at /test/integration/$test-name
  - name: default
    verifier:
      patterns:
        - roles/ansible-pam_yubikey/test/integration/default/serverspec/*_spec.rb
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
