#!/bin/bash

export MOLECULE_IMAGE="quay.io/samdoran/ubuntu18-ansible"
export MOLECULE_DISTRIBUTION="ubuntu"
export MOLECULE_SCENARIO="podman"
export ANSIBLE_VAULT_PASSWORD_FILE="$HOME/.secrets/ansible-ci"
# https://github.com/ansible/ansible/issues/67004
export ANSIBLE_PIPELINING=false
