#!/bin/bash

export MLDISTRO="archlinux"
export MLIMG="archlinux/current"
export ANSIBLE_VAULT_PASSWORD_FILE="$XDG_CONFIG_HOME/ansible/ci-secret"
# https://github.com/ansible/ansible/issues/67004
export ANSIBLE_PIPELINING=false
