#!/bin/bash

export MLDISTRO="ubuntu"
export MLIMG="ubuntu/focal"
export MOLECULE_SCENARIO="default"
export ANSIBLE_VAULT_PASSWORD_FILE="$XDG_CONFIG_HOME/ansible/ci-secret"
# https://github.com/ansible/ansible/issues/67004
export ANSIBLE_PIPELINING=false
