---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: '.direnv/'
platforms:
  - name: "ansible-pam_yubikey-${MOLECULE_DISTRIBUTION:-ubuntu18}"
    image: "${MOLECULE_IMAGE:-quay.io/samdoran/ubuntu18-ansible}"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  options:
    vvv: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
