---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: "ansible-yubikey_${MOLECULE_DISTRIBUTION:-ubuntu18}"
    image: "${MOLECULE_IMAGE:-quay.io/samdoran/ubuntu18-ansible}"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  options:
    vvv: true
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
